{
 "title": "DORA metrics",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT (project_key) FROM build_run"
   },
   {
    "name": "repository_group",
    "label": "Repository group",
    "query": "SELECT DISTINCT (repository_group) \nFROM build_run \nWHERE COALESCE($project) IS NULL OR project_key IN ($project)"
   },
   {
    "name": "repository_name",
    "label": "Repository name",
    "query": "SELECT DISTINCT (repository_name) \nFROM build_run \nWHERE \n(COALESCE($project) IS NULL OR project_key IN ($project)) \nAND (COALESCE($repository_group) IS NULL OR repository_group IN ($repository_group))"
   },
   {
    "name": "build_types",
    "label": "Build types",
    "query": "Feature branch,Integration,Deployment"
   },
   {
    "name": "group_by",
    "label": "Group by",
    "query": "Days : 1d,  Weeks : 1w, Months : 1M, Quarters : 3M"
   },
   { "name": "points_to_average", "label": "Points for trend calculation", "query": "3" }
  ]
 },
 "panels": [
  {
   "title": "Aggregated metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average $build_types count per $group_by",
   "type": "gauge",
   "description": "How often does a team successfully release its system:\n\n- Elite: on demand (multiple deployments per day)\n- High performers: between once per day and once per week\n- Medium performers: between once per week and once per month\n- Low performers: between once per month and once every six months",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Average Commit Delivery Lead Time",
   "type": "gauge",
   "description": "The amount of time it takes a commit to get into production:\n\n- Elite performers: less than one day\n- High performers: between one day and one week\n- Medium performers: between one week and one month\n- Low performers: between one month and six months",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Average $build_types Failure Rate",
   "type": "gauge",
   "description": "The percentage of deployments causing a failure:\n\n- Elite performers: 0-15%\n- High performers: 0-15%\n- Medium performers: 0-15%\n- Low performers: 40-60%",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Average $build_types MTTR",
   "type": "gauge",
   "description": "How long it takes to recover from a failure:\n\n- Elite performers: Less than an hour\n- High performers: Less than one day\n- Medium performers: Less than one day\n- Low performers: Between one week and one month",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Detailed metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$build_types Frequency by $group_by (the more - the better)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroupAlias(build_date, $group_by), \n  SUM(normalized.succeeded) as \"Succeeded\",\n  SUM(normalized.failed) as \"Failed\",\n  AVG(SUM(normalized.succeeded)) OVER (ROWS 3 PRECEDING) AS \"Succeeded Builds Frequency Trend\"\nFROM(\n  SELECT\n    triggered_at::date as build_date,\n    SUM(CASE WHEN build_is_succeeded THEN 1 ELSE 0 END) AS succeeded,\n    SUM(CASE WHEN build_is_succeeded THEN 0 ELSE 1 END) AS failed\n  FROM build_run\n  WHERE (COALESCE($project) IS NULL OR project_key IN ($project))\n    AND (COALESCE($repository_group) IS NULL OR repository_group IN ($repository_group))\n    AND (COALESCE($repository_name) IS NULL OR repository_name IN ($repository_name))\n    AND (COALESCE($build_types) IS NULL OR (is_feature_branch_build AND 'Feature branch' IN ($build_types)) OR (is_integration_build AND 'Integration' IN ($build_types)) OR (is_deployment_build AND 'Deployment' IN ($build_types)))\n  GROUP BY 1\n  ORDER BY build_date\n) AS normalized\nGROUP BY 1\nORDER BY $__timeGroup(build_date, $group_by, 0)"
    }
   ]
  },
  {
   "title": "Commit Delivery Lead Time by $group_by (the less - the better)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT time, \n       \"Commit delivery lead time\",\n       AVG (\"Commit delivery lead time\") OVER (ROWS $points_to_average PRECEDING) AS \"Delivery Lead Time Trend\"\nFROM(\n  SELECT\n    $__timeGroupAlias(build_run.completed_at, $group_by),\n    AVG(EXTRACT(EPOCH FROM (build_run.completed_at-build_commit.commit_date))/60) AS \"Commit delivery lead time\"\n  FROM build_commit\n  INNER JOIN build_run on build_commit.build_run_id = build_run.build_run_id\n  WHERE (is_deployment_build OR is_lead_time_calculation_build)\n    AND build_is_succeeded\n    AND (COALESCE($project) IS NULL OR project_key IN ($project))   \n    AND (COALESCE($repository_group) IS NULL OR repository_group IN ($repository_group))\n    AND (COALESCE($repository_name) IS NULL OR repository_name IN ($repository_name))\n    AND (COALESCE($build_types) IS NULL OR (is_feature_branch_build AND 'Feature branch' IN ($build_types)) OR (is_integration_build AND 'Integration' IN ($build_types)) OR (is_deployment_build AND 'Deployment' IN ($build_types)))\n  GROUP BY 1\n  ORDER BY $__timeGroup(completed_at, $group_by, NULL)\n) AS normalized"
    }
   ]
  },
  {
   "title": "$build_types builds Failure Rate by $group_by (the less - the better)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT time, \"Failure rate\",\n       AVG (\"Failure rate\") OVER (ROWS $points_to_average PRECEDING) AS \"Failure Rate Trend\"\nFROM (\nSELECT\n  $__timeGroupAlias(triggered_at, $group_by),\n  SUM(CASE WHEN build_is_succeeded THEN 0 ELSE 1 END)*100/COUNT(*) AS \"Failure rate\"\nFROM build_run\nWHERE (COALESCE($project) IS NULL OR project_key IN ($project))   \n  AND (COALESCE($repository_group) IS NULL OR repository_group IN ($repository_group))\n  AND (COALESCE($repository_name) IS NULL OR repository_name IN ($repository_name))\n  AND (COALESCE($build_types) IS NULL OR (is_feature_branch_build AND 'Feature branch' IN ($build_types)) OR (is_integration_build AND 'Integration' IN ($build_types)) OR (is_deployment_build AND 'Deployment' IN ($build_types)))\nGROUP BY 1\nORDER BY $__timeGroup(triggered_at, $group_by, NULL)) AS normalized"
    }
   ]
  },
  {
   "title": "$build_types builds MTTR by $group_by (the less - the better)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT time, \"Time to recover\",\n       AVG (\"Time to recover\") OVER (ROWS $points_to_average PRECEDING) AS \"Time To Recover Trend\"\nFROM(\nSELECT\n  $__timeGroupAlias(recovered_at, $group_by),\n  AVG(EXTRACT(EPOCH FROM(recovered_at-first_failed_at))/60) AS \"Time to recover\"\nFROM (\nSELECT project_key, repository_name, repository_group, branch_name, MIN(failed_build_number) as first_failure_number, MIN(failed_at) AS first_failed_at, recovered_at\nFROM (SELECT failed.project_key,\n             failed.repository_name,\n             failed.repository_group,\n             failed.branch_name,\n             failed.build_number AS failed_build_number,\n             failed.triggered_at AS failed_at,\n             MIN(succeeded.triggered_at) AS recovered_at\n        FROM build_run AS failed\n        INNER JOIN (SELECT * FROM build_run WHERE build_is_succeeded) as succeeded\n                ON succeeded.project_key = failed.project_key\n                AND succeeded.repository_name = failed.repository_name\n                AND succeeded.repository_group = failed.repository_group\n                AND succeeded.branch_name = failed.branch_name\n                AND succeeded.triggered_at > failed.triggered_at\n        WHERE (COALESCE($project) IS NULL OR failed.project_key IN ($project))   \n          AND (COALESCE($repository_group) IS NULL OR failed.repository_group IN ($repository_group))\n          AND (COALESCE($repository_name) IS NULL OR failed.repository_name IN ($repository_name))\n          AND (COALESCE($build_types) IS NULL OR (failed.is_feature_branch_build AND 'Feature branch' IN ($build_types)) OR (failed.is_integration_build AND 'Integration' IN ($build_types)) OR (failed.is_deployment_build AND 'Deployment' IN ($build_types)))\n          AND NOT failed.build_is_succeeded\n        GROUP BY failed.project_key, failed.repository_name, failed.repository_group, failed.branch_name, failed_build_number, failed_at\n        ORDER BY failed_at) AS failures_history\nGROUP BY project_key, repository_name, repository_group, branch_name, recovered_at\n) AS failures_history\nGROUP BY 1\nORDER BY $__timeGroup(recovered_at,$group_by, NULL)) as normalized"
    }
   ]
  },
  {
   "title": "Auxiliary data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$build_types builds history",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(project_key, ' ', repository_name, ' (', branch_name, ')') AS \"project\",\n  build_result AS \"result\",\n  CASE \n    WHEN is_deployment_build THEN 'Deployment'\n    WHEN is_integration_build THEN 'Integration'\n    WHEN is_lead_time_calculation_build THEN 'Lead Time calculation'\n    WHEN is_feature_branch_build THEN 'Feature branch'\n    ELSE '-' \n  END AS \"build type\",\n  completed_at AS \"completed at\",\n  build_run_id AS \"link\"\nFROM build_run\nWHERE\n  $__timeFilter(triggered_at) \n  AND (COALESCE($project) IS NULL OR project_key IN ($project))\n  AND (COALESCE($repository_group) IS NULL OR repository_group IN ($repository_group))\n  AND (COALESCE($repository_name) IS NULL OR repository_name IN ($repository_name))\n  AND (COALESCE($build_types) IS NULL OR (is_feature_branch_build AND 'Feature branch' IN ($build_types)) OR (is_integration_build AND 'Integration' IN ($build_types)) OR (is_deployment_build AND 'Deployment' IN ($build_types)))\nORDER BY $__timeGroup(triggered_at, $group_by, 0)"
    }
   ]
  },
  {
   "title": "$build_types pipeline average duration by $group_by",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(triggered_at, $group_by),\n  AVG(total_duration_in_seconds) AS \"Avg duration\",\n  AVG(AVG(total_duration_in_seconds)) OVER (ROWS 3 PRECEDING) AS \"Avg Duration Trend\"\nFROM build_run\nWHERE build_is_succeeded\n  AND (COALESCE($project) IS NULL OR project_key IN ($project))\n  AND (COALESCE($repository_group) IS NULL OR repository_group IN ($repository_group))\n  AND (COALESCE($repository_name) IS NULL OR repository_name IN ($repository_name))\n  AND (COALESCE($build_types) IS NULL OR (is_feature_branch_build AND 'Feature branch' IN ($build_types)) OR (is_integration_build AND 'Integration' IN ($build_types)) OR (is_deployment_build AND 'Deployment' IN ($build_types)))\nGROUP BY 1\nORDER BY $__timeGroup(triggered_at, $group_by, NULL)"
    }
   ]
  },
  {
   "title": "$build_types pipeline average wait time by $group_by",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(triggered_at, $group_by),\n  AVG(wait_duration_in_seconds) AS \"Avg wait time\",\n  AVG(AVG(wait_duration_in_seconds)) OVER (ROWS 3 PRECEDING) AS \"Avg wait time Trend\"\nFROM build_run\nWHERE build_is_succeeded \n  AND wait_duration_in_seconds IS NOT NULL\n  AND (COALESCE($project) IS NULL OR project_key IN ($project))\n  AND (COALESCE($repository_group) IS NULL OR repository_group IN ($repository_group))\n  AND (COALESCE($repository_name) IS NULL OR repository_name IN ($repository_name))\n  AND (COALESCE($build_types) IS NULL OR (is_feature_branch_build AND 'Feature branch' IN ($build_types)) OR (is_integration_build AND 'Integration' IN ($build_types)) OR (is_deployment_build AND 'Deployment' IN ($build_types)))\nGROUP BY 1\nORDER BY $__timeGroup(triggered_at, $group_by, NULL)"
    }
   ]
  },
  {
   "title": "$build_types tests stats",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    test_name AS \"Test name\",\n    COUNT(*) AS \"Total runs count\",\n    COUNT(CASE WHEN test_status IN ('FAILED', 'REGRESSION') THEN 1 ELSE NULL END) AS \"Failures count\",\n    COUNT(CASE WHEN test_status IN ('FAILED', 'REGRESSION') THEN 1 ELSE NULL END)::decimal/COUNT(*) AS \"Flakiness rate\",\n    STRING_AGG(DISTINCT CASE WHEN test_status IN ('FAILED', 'REGRESSION') THEN build_run.build_run_id ELSE '' END, '\\n') AS \"Failed in builds\",\n    AVG(test_duration) AS \"AVG duration\"\nFROM build_run\nINNER JOIN build_run_test ON build_run.build_run_id = build_run_test.build_run_id\nWHERE\n  $__timeFilter(triggered_at)\n  AND build_run_test.exclude_from_stats=False\n  AND (COALESCE($project) IS NULL OR project_key IN ($project))\n  AND (COALESCE($repository_group) IS NULL OR repository_group IN ($repository_group))\n  AND (COALESCE($repository_name) IS NULL OR repository_name IN ($repository_name))\n  AND (COALESCE($build_types) IS NULL OR (is_feature_branch_build AND 'Feature branch' IN ($build_types)) OR (is_integration_build AND 'Integration' IN ($build_types)) OR (is_deployment_build AND 'Deployment' IN ($build_types)))\nGROUP BY build_run_test.test_name\nORDER BY \"Failures count\" DESC"
    }
   ]
  }
 ]
}