{
 "title": "Project security dashboard",
 "time": { "from": "2022-12-31T22:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "product_type",
    "label": "Product type",
    "query": "SELECT \n   product_type_id  AS __value,\n   CONCAT(product_type_name, ' (', SUM(case when active then 1 ELSE 0 end), ' active findings, ', SUM(case when active then severity_weight ELSE 0 end), ' index points)') AS __text\nFROM security_dashboard_data\nGROUP BY product_type_id, product_type_name\nORDER BY SUM(case when active then severity_weight ELSE 0 end) DESC"
   },
   {
    "name": "product",
    "label": "Product",
    "query": "SELECT \n   product_id  AS __value,\n   CONCAT(product_name, ' (', SUM(case when active then 1 ELSE 0 end), ' active findings, ', SUM(case when active then severity_weight ELSE 0 end), ' index points)') AS __text\nFROM security_dashboard_data\nWHERE (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\nGROUP BY product_id, product_name\nORDER BY SUM(case when active then severity_weight ELSE 0 end) DESC"
   },
   {
    "name": "service",
    "label": "Repository",
    "query": "SELECT \n   COALESCE(service, '--no repository--')  AS __value,\n   CONCAT(COALESCE(service, '--no repository--'), ' (', SUM(case when active then 1 ELSE 0 end), ' active findings, ', SUM(case when active then severity_weight ELSE 0 end), ' index points)') AS __text\nFROM security_dashboard_data\nWHERE (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n         AND (COALESCE($product) IS NULL OR product_id IN ($product))\nGROUP BY service\nORDER BY SUM(case when active then severity_weight ELSE 0 end) DESC"
   },
   {
    "name": "component",
    "label": "Component",
    "query": "SELECT COALESCE(component_name, '--no component--') AS __value, \nCONCAT(COALESCE(component_name, '--no component--'), ' (', SUM(case when active then 1 ELSE 0 end), ' active findings, ', SUM(case when active then severity_weight ELSE 0 end), ' index points)') AS __text\n         FROM security_dashboard_data\nWHERE (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n         AND (COALESCE($product) IS NULL OR product_id IN ($product))\n         AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\nGROUP BY component_name\nORDER BY SUM(case when active then severity_weight ELSE 0 end) DESC"
   },
   {
    "name": "tool",
    "label": "Tool",
    "query": "SELECT test_type_id as __value, \nCONCAT(test_type_name, ' (', SUM(case when active then 1 ELSE 0 end), ' active findings, ', SUM(case when active then severity_weight ELSE 0 end), ' index points)') AS __text\n         FROM security_dashboard_data\nWHERE (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n         AND (COALESCE($product) IS NULL OR product_id IN ($product))\n         AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\nGROUP BY test_type_id, test_type_name\nORDER BY SUM(case when active then severity_weight ELSE 0 end) DESC"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "SELECT severity_weight, severity as __value, \nCONCAT(severity, ' (', SUM(case when active then 1 ELSE 0 end), ' active findings, ', SUM(case when active then severity_weight ELSE 0 end), ' index points)') AS __text\n         FROM security_dashboard_data\nWHERE (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n         AND (COALESCE($product) IS NULL OR product_id IN ($product))\n         AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\nGROUP BY severity_weight, severity\nORDER BY severity_weight DESC, severity DESC"
   },
   {
    "name": "group_by",
    "label": "Group by",
    "query": "Days : 1d,  Weeks : 1w, Months : 1M, Quarters : 3M"
   },
   { "name": "defect_dojo_url", "query": "${VAR_DEFECT_DOJO_URL}" }
  ]
 },
 "panels": [
  {
   "title": "Currently active findings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Resolved vs created dynamics for  ${__from:date:YYYY.MM.DD} - ${__to:date:YYYY.MM.DD}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Resolved findings\", \"Created findings\", \"Resolved findings\"-\"Created findings\" AS \"Delta\" \nFROM\n    (SELECT COALESCE(COUNT(*), 0) as \"Created findings\"\n    FROM security_dashboard_data\n    WHERE $__timeFilter(created)\n        AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n        AND (COALESCE($product) IS NULL OR product_id IN ($product))\n        AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n        AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n        AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n        AND (COALESCE($severity) IS NULL OR severity IN ($severity))) AS index_growth\nJOIN \n    (SELECT COALESCE(COUNT(*), 0) AS \"Resolved findings\"\n    FROM security_dashboard_data\n    WHERE active = False\n        AND $__timeFilter(last_handle_date)\n        AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n        AND (COALESCE($product) IS NULL OR product_id IN ($product))\n        AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n        AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n        AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n        AND (COALESCE($severity) IS NULL OR severity IN ($severity))) AS index_reduction\nON 1=1"
    }
   ]
  },
  {
   "title": "Current security index",
   "type": "stat",
   "description": "A summary index calculated as the number of findings multiplied by their \"severity weight\". Severity weights are the following:\n- Critical = 1000\n- High = 100\n- Medium = 10\n- Low, Info = 1",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Security index dynamics for  ${__from:date:YYYY.MM.DD} - ${__to:date:YYYY.MM.DD}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Index reduction\", \"Index growth\", \"Index reduction\"-\"Index growth\" AS \"Delta\" \nFROM\n    (SELECT COALESCE(SUM(severity_weight), 0) as \"Index growth\"\n    FROM security_dashboard_data\n    WHERE $__timeFilter(created)\n        AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n        AND (COALESCE($product) IS NULL OR product_id IN ($product))\n        AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n        AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n        AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n        AND (COALESCE($severity) IS NULL OR severity IN ($severity))) AS index_growth\nJOIN \n    (SELECT COALESCE(SUM(severity_weight), 0) AS \"Index reduction\"\n    FROM security_dashboard_data\n    WHERE active = False\n        AND $__timeFilter(last_handle_date)\n        AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n        AND (COALESCE($product) IS NULL OR product_id IN ($product))\n        AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n        AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n        AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n        AND (COALESCE($severity) IS NULL OR severity IN ($severity))) AS index_reduction\nON 1=1"
    }
   ]
  },
  {
   "title": "Findings statistics for ${__from:date:YYYY.MM.DD} - ${__to:date:YYYY.MM.DD}",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n    COALESCE(handled.time, created.time) AS time,\n        SUM(COALESCE(index_increment, 0) - COALESCE(index_decrement, 0)) OVER(ORDER BY COALESCE(handled.time, created.time) ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS \"Security index\",\n    SUM(COALESCE(handled_count,0)) OVER(ORDER BY COALESCE(handled.time, created.time) ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS \"Resolved findings count\",\n    SUM(COALESCE(created_count,0)) OVER(ORDER BY COALESCE(created.time, handled.time) ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS \"Created findings count\",\n    SUM(COALESCE(created_count,0)) OVER(ORDER BY COALESCE(created.time, handled.time) ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) \n        - SUM(COALESCE(handled_count,0)) OVER(ORDER BY COALESCE(handled.time, created.time) ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS \"Active findings count\"\n\nFROM\n    (SELECT\n         $__timeGroupAlias(last_handle_date, $group_by),\n         COUNT(*) AS handled_count,\n         SUM(severity_weight) AS index_decrement\n     FROM security_dashboard_data\n     WHERE \n        active = False\n        AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n        AND (COALESCE($product) IS NULL OR product_id IN ($product)) \n        AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service)) \n        AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n        AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool)) \n        AND (COALESCE($severity) IS NULL OR severity IN ($severity))\n     GROUP BY 1) AS handled\n        FULL JOIN\n    (SELECT\n         $__timeGroupAlias(created, $group_by),\n         COUNT(*) AS created_count,\n         SUM(severity_weight) AS index_increment\n     FROM security_dashboard_data\n     WHERE (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n        AND (COALESCE($product) IS NULL OR product_id IN ($product)) \n        AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service)) \n        AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n        AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool)) \n        AND (COALESCE($severity) IS NULL OR severity IN ($severity))\n     GROUP BY 1) AS created\n    ON handled.time = created.time\nWHERE COALESCE(handled.time, created.time) IS NOT NULL"
    }
   ]
  },
  {
   "title": "Active findings",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \n    title,\n    severity_weight,\n    COALESCE(EXTRACT(EPOCH FROM (created + make_interval(days => days_to_fix_by_sla))-current_timestamp), 0) AS \"Time to fix by SLA\",\n    description,\n    service,\n    file_path,\n    component_name,\n    test_type_id,\n    test_type_name,\n    cve,\n    product_id,\n    product_name,\n    created,\n    id,\n    source_code_management_uri,\n    line_number,\n    product_type_id\nFROM security_dashboard_data\nWHERE active = True\n    AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n    AND (COALESCE($product) IS NULL OR product_id IN ($product))\n    AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n    AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n    AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n    AND (COALESCE($severity) IS NULL OR severity IN ($severity))\nORDER BY created DESC"
    }
   ]
  },
  {
   "title": "Average remediation time by finding date",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('MONTH', created) AS time, \nCOUNT(*) AS mitigated_findings_count,\nAVG(EXTRACT(epoch from last_handle_date::timestamp - created::timestamp)) as mitigated_findings_age\nFROM security_dashboard_data\nWHERE active = False\n    AND $__timeFilter(created)\n    AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n    AND (COALESCE($product) IS NULL OR product_id IN ($product))\n    AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n    AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n    AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n    AND (COALESCE($severity) IS NULL OR severity IN ($severity))\nGROUP BY time\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Average active finding age for ${__from:date:YYYY.MM.DD HH:mm:SS} - ${__to:date:YYYY.MM.DD HH:mm:SS}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(epoch from CURRENT_DATE::timestamp - created::timestamp) as finding_age\nFROM security_dashboard_data\nWHERE active = True\n    AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n    AND (COALESCE($product) IS NULL OR product_id IN ($product))\n    AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n    AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n    AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n    AND (COALESCE($severity) IS NULL OR severity IN ($severity))\n"
    }
   ]
  },
  {
   "title": "Average finding remediation time for ${__from:date:YYYY.MM.DD HH:mm:SS} - ${__to:date:YYYY.MM.DD HH:mm:SS}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(epoch from last_handle_date::timestamp - created::timestamp) as finding_age\nFROM security_dashboard_data\nWHERE active = False\n    AND $__timeFilter(last_handle_date)\n    AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n    AND (COALESCE($product) IS NULL OR product_id IN ($product))\n    AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n    AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n    AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n    AND (COALESCE($severity) IS NULL OR severity IN ($severity))"
    }
   ]
  },
  {
   "title": "Top 20 CVE by index contribution",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT \n    cve,\n    SUM(severity_weight) as index_contribution\nFROM security_dashboard_data\nWHERE active = True AND cve IS NOT NULL\n    AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n    AND (COALESCE($product) IS NULL OR product_id IN ($product))\n    AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n    AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n    AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n    AND (COALESCE($severity) IS NULL OR severity IN ($severity))\nGROUP BY cve\nORDER BY index_contribution DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Active findings opened during ${__from:date:YYYY.MM.DD HH:mm:SS} to ${__to:date:YYYY.MM.DD HH:mm:SS}",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT \n    title,\n    severity_weight,\n    COALESCE(EXTRACT(EPOCH FROM (created + make_interval(days => days_to_fix_by_sla))-current_timestamp), 0) AS \"Time to fix by SLA\",\n    description,\n    service as repository,\n    file_path,\n    component_name,\n    test_type_name,\n    test_type_id,\n    cve,\n    product_id,\n    product_name,\n    created,\n    id,\n    source_code_management_uri,\n    line_number,\n    product_type_id\nFROM security_dashboard_data\nWHERE active=True \n    AND $__timeFilter(created)\n    AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n    AND (COALESCE($product) IS NULL OR product_id IN ($product))\n    AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n    AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n    AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n    AND (COALESCE($severity) IS NULL OR severity IN ($severity))\nORDER BY created DESC"
    }
   ]
  },
  {
   "title": "Findings handled during ${__from:date:YYYY.MM.DD HH:mm:SS} - ${__to:date:YYYY.MM.DD HH:mm:SS}",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "rawSql": "SELECT \n    title,\n    severity_weight,\n    test_type_name,\n    test_type_id,\n    mitigated_by,\n    last_handle_date,\n    resolution_status,\n    description,\n    cve,\n    product_id,\n    product_name,\n    service,\n    component_name,\n    created,\n    id\nFROM security_dashboard_data\nWHERE active = False\n    AND $__timeFilter(last_handle_date)\n    AND (COALESCE($product_type) IS NULL OR product_type_id IN ($product_type))\n    AND (COALESCE($product) IS NULL OR product_id IN ($product))\n    AND (COALESCE($service) IS NULL OR ('--no repository--' IN ($service) AND service IS NULL) OR service IN ($service))\n    AND (COALESCE($component) IS NULL OR ('--no component--' IN ($component) AND component_name IS NULL) OR component_name IN ($component)) \n    AND (COALESCE($tool) IS NULL OR test_type_id IN ($tool))\n    AND (COALESCE($severity) IS NULL OR severity IN ($severity))\nORDER BY last_handle_date DESC"
    }
   ]
  }
 ]
}